### PR TITLE
Async conversion

### PR DESCRIPTION
**Pull request by unreadablewxy**

### CODE REVIEW

**Comment by unreadablewxy** [comment]
As per issue #3, this change inverts control from callback passing to an async stream (thus the major version bump). It includes a workable demo program to show how it works and has been verified against an actual production use case

**Comment by RandomEngy** [comment]
This is epic. I'm going to look at it over this weekend.

**Comment by RandomEngy** [comment]
Got my app converted over on top of this PR, seems to work fine! Will need to update the README with the new code as well before I can release it.

**Comment by RandomEngy** [comment]
I do have one question: is there a reason why you expose the raw bytes on the body rather than the payload JSON? It seems like this is always going to be a JSON string for FCM, right?

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message

**Comment by RandomEngy** [comment]
You expose `new_heartbeat_ack()` externally and acknowledging heartbeats is no longer in the library itself. Is there a reason we can't ack the heartbeats automatically? Seems like it would reduce the number of potential ways to fail using the library.

**Comment by unreadablewxy** [comment]
There's no reason why the lib can't auto ack heartbeats. I had it exposed to the caller to add metrics on its frequency and test what happens if I didn't ack them. Protocol docs are a bit lackluster and I was curious. No opposition to the having the receiver auto ack heartbeats

**Comment by RandomEngy** [comment]
Could you add that in as well? Just a code snippet if it's easy. It's not immediately obvious how to do that with the new streaming approach.

`self.write(&new_heartbeat_ack()).await?;` does not work because the block is not async.

**Comment by RandomEngy** [comment]
I'm curious, is this something that you'd be able to find time to do to finish up the conversion?

**Comment by RandomEngy** [comment]
I did some more testing in preparation for a potential v4 release. Heartbeats come down on the connection every 30 minutes. I noticed that now we get just one heartbeat 30 minutes after connecting, then the connection goes dead until it's restarted. That is, I send push messages to FCM but they don't show up in the message stream. I think this is because we don't ack the heartbeats anymore. Before this PR the connection would stay open for hours, and we'd see heartbeats all the way through.

It would be an annoyance to require manual heartbeat acks from a new version, so I don't want to release v4 until that happens. But it does not look trivial to do it. I was thinking that if we had something that could wrap the gcm checkin and stream creation, and that auto-acked heartbeats before exposing them on the message stream, that would be ideal.

I don't really *need* to release a new version right away, but if something comes up where I have to release some extra changes, I'd have to revert this PR before doing it.

**Comment by RandomEngy** [comment]
Ehh actually I do need the heartbeat info to inform when I need to reconnect. I'll just publish v4 and we can just do a v5 if this is ever fixed.

**Pull request merged**
